name: Publish to NPM

env:
  package: serverless-step-functions

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.target_commitish }}
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/
    - run: echo "VERSION=${{ github.event.release.tag_name }}" # strip the package out of the release name
    - run: npm ci
    - run: git config --global user.name "Automated NPM Release"
    - run: git config --global user.email "sysadmin+npm-deploy@aligent.com.au"
    - run: npm version $VERSION --allow-same-version --workspace "@aligent/${package}"
    - run: npm run build --workspace "@aligent/${package}"
    - run: npm test --workspace "@aligent/${package}" --if-present
    - run: npm publish --access public --workspace "@aligent/${package}"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: git push
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}

